services:
  # Spring Boot Application Service (Web Service)
  - type: web
    name: osls-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: osls-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: osls-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: osls-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: osls-db
          property: password
      - key: DB_DATABASE
        fromDatabase:
          name: osls-db
          property: database
      - key: DB_SSL_MODE
        value: require

databases:
  # Managed PostgreSQL Database Service (Free Tier)
  - name: osls-db
    plan: free
